apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-account-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.1"
  POD_NAME: "go-account-local.k8"
  PORT: "5000"
  DB_HOST: "0.0.0.0"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  SETPOD_AZ: "false"
  TLS: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: "localhost:4317"
  ENV: "dev"