apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-account-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "3.2"
  POD_NAME: "go-account-02.arch-eks-01-02"
  PORT: "5000"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  DB_MAX_CONNECTION: "80"
  CTX_TIMEOUT: "5"
  SETPOD_AZ: "false"
  ENV: "dev"

  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-02-otel-collector-collector.default.svc.cluster.local:4317"
  USE_STDOUT_TRACER_EXPORTER: "false"
  USE_OTLP_COLLECTOR: "true" 
  AWS_CLOUDWATCH_LOG_GROUP_NAMES: "/dock/eks/eks-arch-01-02"

